auth:
  adminUser: admin
  adminPassword: admin4admin
proxyAddressForwarding: true
service:
  type: ClusterIP
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  path: /
  pathType: Prefix
  hostname: auth.maxilog.me
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
