serviceAccountAgent:
  create: false
controller:
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    hostName: "jenkins.maxilog.me"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: jenkins.maxilog.me-tls
        hosts:
          - jenkins.maxilog.me
